shopping_list="Shopping List"
default_="Default"

[list_header]
item_name="Item Name"
amount="Amount"

[item]
edit="Edit"
remove="Remove"
remove_question_1="Do you want to remove "
remove_question_2="?"
